登录用户名: "//*[@placeholder='请输入用户名']"               # 用户名 输入框
登录密码: "//*[@placeholder='请输入密码']"                  # 密码 输入框
登录按钮: "//*[@type='button']"                           # 登录按钮

模块: "//*[@alt='{0}']"                                  # 菜单上的模块
菜单: "//span[contains(text(), '{0}')]"                  # 左侧菜单
子菜单: "//li[{0}]/ul/li[text()='{1}']"                  # 左侧子菜单
查询按钮: "//button/span[contains(text(), '{0}')]"        # 各个页面上的查询按钮
提示框: "//div[@role='alert']"                           # 提示弹窗（不知道定位得到不...）