登录用户名: "//*[@placeholder='请输入用户名']"            # 用户名 输入框
登录密码: "//*[@placeholder='请输入密码']"               # 密码 输入框
登录按钮: "//*[@type='button']"                        # 登录按钮
操作员名称: "//*[@class='user']/span/button/span"       # 验证登录后右上角的名称是否正确

模块: "//*[@alt='{0}']"                               # 菜单上的模块
菜单: "//span[contains(text(), '{0}')]"               # 左侧菜单
子菜单: "//li[{0}]/ul/li[text()='{1}']"                # 左侧子菜单
查询按钮: "//button/span[contains(text(), '{0}')]"     # 各个页面上的查询按钮
提示框: "//div[@role='alert']"                         # 提示弹窗（不知道定位得到不...）

征订目录-详情页面: "//*/tbody/tr[1]/td[3]/div/span"      # 详情链接

筛选项: "//div[@class='header__line']/div[{0}]"                              # 筛选项
筛选-单选列表: "//div[@x-placement='bottom-start']/div[1]/div[1]/ul/li"       # 点击 筛选项弹出的单选列表
筛选-开始日期: "//input[@placeholder='开始日期']"                               # 开始日期输入框
筛选-结束日期: "//input[@placeholder='结束日期']"                               # 结束日期输入框
筛选-征订目录: "//input[@placeholder='请输入征订目录']"                          # 征订目录输入框

右上按钮: "//div[@class='header__ops']/button[{0}]"           # 获取右上角的按钮
